Additional resources
vovopap/coding-interview-university pull request #5
Opened 2021-04-23 17:31 UTC by elzodxon

2021-04-28 07:32 UTC, vovopap requested changes

2021-04-28 07:32 UTC, vovopap commented on translations/README-uz.md
>      - [Emacs and vi(m)](#emacs-and-vim)
Bu yer qolib ketibdi

2021-04-28 07:32 UTC, vovopap commented on translations/README-uz.md
> +    - [Unix buyruqlar satri vositalari(command line tools)](#unix-command-line-tools)
Buni shundoqligicha qoldirgan yaxshi deb uylayman. Hamma command line deydiku baribir

2021-04-28 07:32 UTC, vovopap commented on translations/README-uz.md
>      - [Messaging, Serialization, and Queueing Systems](#messaging-serialization-and-queueing-systems)
"and" ni tarjima qilib qo'ying

2021-04-28 07:32 UTC, vovopap commented on translations/README-uz.md
> +    - [Geometriya, Convex korpusi](#geometry-convex-hull-videos)
Convex hull shunday qolgani yaxshi

2021-04-28 07:32 UTC, vovopap commented on translations/README-uz.md
>  - [Additional Detail on Some Subjects](#additional-detail-on-some-subjects)
bu yerni tarjima qilish kerak

2021-04-28 07:32 UTC, vovopap commented on translations/README-uz.md
>  - [Papers](#papers)
Paperni ilmiy ish deb tarjima qilsa buladi

2021-04-28 07:32 UTC, vovopap commented on translations/README-uz.md
> +sdhfsdfdsjdf
Buni qaytarib quying

2021-05-14 18:48 UTC, elzodxon commented
Conflict:)

2021-06-07 07:43 UTC, vovopap commented
Closing due to inactivity

2021-06-07 07:43 UTC, closed without merging